receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317
      http:
        endpoint: otel-collector:4318
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

processors:
  dedupeprocessor:

exporters:
  debug:
  file:
    path: ./file-exporter/otelcol_traces.json

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [dedupeprocessor]
      exporters: [debug, file]
